version: '3.7'
services:
  backend:
    container_name: my-s3
    build:
      dockerfile: ./dockerfile
      context: ./
    image: efrei/my-s3
    ports:
      - "4242:4242"
    networks:
      - turreta_network
    depends_on:
      - postgres
  postgres:
   container_name: my-s3_db
   image: "postgres:13"
   restart: "always"
   ports:
      - "5434:5432"
   environment:
     - POSTGRES_USER=user_api
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=my-s3_db
   networks:
     - turreta_network
networks:
  turreta_network:
    driver: bridge